MOD-8197 Unified CI workflows (#1304)
- Updated and added new GitHub Actions workflows for build, test, and deployment
- Introduced event-based workflows for specific triggers:
    - `event-ci.yml`: Runs CI checks on pull requests and pushes to specific branches
    - `event-nightly.yml`: Executes nightly builds and tests
    - `event-tag.yml`: Triggers workflows on new tags for release processes
- Differentiated flow-based workflows for various environments:
    - `flow-alpine.yml`: Handles builds and tests for Alpine Linux
    - `flow-linux-x86.yml`: Manages workflows for x86 Linux distributions
    - `flow-macos.yml`: Manages workflows for macOS environments
    - `flow-ubuntu-arm.yml`: Handles builds and tests for Ubuntu on ARM architecture
- Removed obsolete workflows
- Added new installation scripts for various Linux distributions and macOS
- Modified existing scripts and configurations for better compatibility and performance

diff --git a/.github/actions/upload-artifacts-to-s3/action.yml b/.github/actions/upload-artifacts-to-s3/action.yml
--- a/.github/actions/upload-artifacts-to-s3/action.yml
+++ b/.github/actions/upload-artifacts-to-s3/action.yml
@@ -20,12 +20,6 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v3
-      with: # todo: use role instead of access key
-        aws-access-key-id: ${{ inputs.aws-access-key-id }}
-        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
-        aws-region: "us-east-1"
     - name: Upload artifacts to S3 - staging
       shell: bash
       run: |
@@ -33,6 +27,22 @@ runs:
           python3 -m venv .aws-cli-venv && source .aws-cli-venv/bin/activate &&
           pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
         echo ::endgroup::
+        
+        # Variables from the workflow
+        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
+        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
+        export AWS_REGION="us-east-1"
+        # Check if the required environment variables are set
+        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
+          echo "Missing AWS credentials or region configuration."
+          exit 1
+        fi
+        # Configure AWS CLI with provided credentials and region
+        echo "Configuring AWS CLI with access keys..."
+        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
+        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
+        aws configure set region "$AWS_REGION"
+
         echo ::group::upload artifacts
           make upload-artifacts SHOW=1 VERBOSE=1
         echo ::endgroup::
